openapi: 3.0.2
info:
  title: isgood webAPI
  description: The interface to DS for consumers like the isgood webApp
  version: 0.1.1
  license:
    name: GNU Affero General Public License v3.0
    url: 'https://github.com/for-good/isgood-api/blob/main/LICENSE'
paths:
  /indicators:
    post:
      description: Find recommended indicators based on criteria
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IndicatorsRequest'
      responses:
        '200':
          description: List of numbers representing vector
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IndicatorsResponse'
        default:
          description: Unexpected error
components:
  schemas:
    IndicatorsRequest:
      type: object
      required:
        - projectId
        - name
        - description
        - projectImpacts
        - outcomesDesired
      properties:
        projectId:
          type: string
        name:
          type: string
        description:
          type: string
        projectImpacts:
          type: array
          items:
            type: string
        outcomesDesired:
          type: array
          items:
            type: string
    Indicators:
      type: object
      properties:
        projectId:
          type: string
        indicators:
          type: array
          items:
            type: object
            properties:
              indicatorID:
                type: number
              alignedStrength:
                type: number
    IndicatorsResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Indicators'
  securitySchemes:
    isgoodUserPool:
      type: apiKey
      name: Authorization
      in: header
      x-amazon-apigateway-authtype: cognito_user_pools
      x-amazon-apigateway-authorizer:
        type: cognito_user_pools
        providerARNs:
          - arn:aws:cognito-idp:{region}:{account_id}:userpool/{user_pool_id}
security:
  - isgoodUserPool: []
