openapi: 3.0.0
info:
  title: isgood webAPI
  description: The interface to DS for consumers like the isgood webApp
  version: 0.0.1
components:
  schemas:
    Indicator:
      type: object
      properties:
          id:
            type: integer
          name:
            type: string

paths:
  /recommendations:
    get:
      summary: Get recommended indicators for a project according to criteria
      parameters:
        - in: query
          name: criteria
          schema:
            type: string
          required: true
          description: The four project info text (comma-separated values) that will be searched for recommended indicators
      responses:
        '200':
          description: A JSON array of indicators
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Indicator'
        '400':
          description: The specified criteria is not a string.
        default:
          description: Unexpected error

