name: "Terratest"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terratest:
    name: "Terratest"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tests/infrastructure

    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.15'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2
      - name: Go dependencies
        run: |
          go mod init github.com/patterns/hello-terratest

      - name: Run Terratest
        ##        env:
                ##          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
        run: go test -v -count=1 -timeout 30m

                ##          echo "credentials \"app.terraform.io\" { token = \"$TF_API_TOKEN\" }" > ~/.terraformrc
                ##          go test -v -count=1 -timeout 30m



